### ISSUE TITLE
Binding parameters from multiple locations not working in .NET 6?

### ISSUE THREAD

**Issue by luuk777w** [ardalis/ApiEndpoints#161] opened 2021-10-16 23:59 UTC
- NuGet Package Version: 3.1.0
- .NET SDK Version: 6.0-RC-1

I am trying to bind parameters from multiple locations as specified in the documentation, but it does not seem to work. 

**Endpoint:**
```c#
[HttpPut("api/projects/{projectId}")]
public override async Task<ActionResult<UpdateProjectResponse>> HandleAsync([FromRoute] UpdateProjectRequest request, CancellationToken cancellationToken = default)
{

}
```
**Request:**
```c#
public class UpdateProjectRequest
{
    [FromRoute(Name = "projectId")] public Guid ProjectId { get; set; } = default!;

    [FromBody] public string Code { get; set; } = default!;

    [FromBody] public string Description { get; set; } = default!;

    [FromBody] public string Number { get; set; } = default!;
}

```

This is the response I get:

```json
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-8204c6f7087a1e60fb4c1ab5ac75c778-de42a5cad4fe62d6-00",
  "errors": {
    "$": [
      "The JSON value could not be converted to System.String. Path: $ | LineNumber: 0 | BytePositionInLine: 1.",
      "The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0."
    ],
    "Code": [
      "The Code field is required.",
      "'Code' must not be empty."
    ],
    "Number": [
      "The Number field is required.",
      "'Number' must not be empty."
    ],
    "Description": [
      "The Description field is required.",
      "'Description' must not be empty."
    ]
  }
}
```

I am also using FluentValidation, but that should not matter because FluentValidation validates after model binding.

Could this be because something has changed in .NET 6 or am I just missing something?

**Comment by Allann** [comment] 2021-11-23 03:16
I am not having exactly the same result as described above, I do however not get the Id from the route (though it is displayed in swagger ui as a required route parameter), but the body also includes the id and this is what is being bound to the command object.

Not sure whether this is a swagger issue or an ApiEndpoint issue.

**Comment by kerpekri** [comment] 2022-01-12 08:39
Hello, well it works as @Allann suggested, but feels not perfect 💯

**Comment by ardalis** [comment] 2022-01-17 21:03
@Allann @luuk777w Can you confirm if this is still an issue in 4.x? We redid a bunch of things so this may have been fixed along the way.

**Comment by luuk777w** [comment] 2022-01-17 21:36
@ardalis I have just tested it and the issue remains. I have created a reproduction repo: https://github.com/luuk777w/ApiEndpointsIssueRepro

**Comment by luuk777w** [comment] 2022-01-17 21:42
What I have done myself as a workaround is creating a BaseAsyncEndpoint myself with multiple WithResponse classes. One with only one parameter, one with two parameters etc.

I have done it like this: https://gist.github.com/luuk777w/5f8d1a7a6f178da4884e87ca7c0b9e38
It works really well, and as a bonus it plays nice with Swagger. However, the downside of this approach is that you will limit the number of parameters by how many classes you make.

**Comment by ardalis** [comment] 2022-01-27 22:22
@luuk777w Hmm, that's not bad. I personally prefer to have a single request per endpoint if possible, but obviously it's a very common scenario to have data coming in from multiple sources (route, query, body), which causes problems with the default model binding. So, I wouldn't see a problem with defining *at most* 3 or 4 request types on the signature, so that you could have one or two for route arguments, one for query, one for body, etc.

Something to research:
If you have 3 Request types modeled as classes, lets' call them `FooRouteRequest`, `FooQueryRequest`, and `FooBodyRequest` and you marked them like this:

```csharp
public async Task<ActionResult<FooResponse>> HandleAsync(
    [FromRoute] FooRouteRequest routeRequest,
    [FromQuery] FooQueryRequest queryRequest,
    [FromBody] FooBodyRequest bodyRequest,
    CancellationToken cancellationToken = default)
{ ... }
```

Would everything bind as expected?

**Comment by nhwilly** [comment] 2022-02-01 23:02
So, if I want to pick up a `tenantId` from the headers or the route, I'd have to do something like this.  

I prefer the headers because every use of the app will be in the context of the tenant and I don't want to pollute all the routes with that.

I'm too 🐔 to tinker with this really cool package.  

I guess I'll try to create an extension method that gets what I want from the headers in the controller.

**Comment by ardalis** [comment] 2022-02-01 23:27
Ok, maybe I would need up to 4 request types, to support headers as well.

BTW, thanks for the sponsor, @nhwilly !

**Comment by ardalis** [comment] 2022-02-01 23:29
@nhwilly did you try any of these approaches yet?
https://stackoverflow.com/questions/57768912/how-to-use-fromheader-attribute-with-custom-model-binding-in-asp-net-core-2-2

**Comment by nhwilly** [comment] 2022-02-02 15:23
Thanks for the quick response.

Didn't even know that was possible.  And I'm not sure it is.  It seems to work well if you're using `[FromQuery]` and `[FromHeader]` together, but the minute you try to get anything from the body using `[FromBody]`, it doesn't seem to bind.

Once upon a time, I wrote an `ActionFilter` (I think) that looked on the model for an `IAccountable` attribute.  If it found it, it pulled the data from the header and stuffed it into the model property before moving on.

Since I'll be running an `AuthorizationFilter` (still called that?) earlier in the pipeline to set user claims (permissions), there's a database call in place already to ensure that we're receiving a valid `tenantId`.

I'm not sure how I can update a property without bypassing the constructor, which means a `SetTenantId(int id)` method exists, or a mapping has to occur. Ugh.

Since the endpoint is being constructed as an API, I can't really assume my Blazor app is constructing all the requests properly.

I guess I could create yet another request object that derived from original and contained the `tenantId`.  So...

In your example, `CreateProject` would contain the project name and in the `ActionFilter` I instantiate a `CreateTenantProject` that has the `CreateProject` and `TenantId` as properties.  The endpoint would be looking for the `CreateTenantProject`.

Guard clauses all around.  Seems cluttery, but it's probably the safest approach.

Is that possible?  Can I morph one type into another in the pipeline like that?  Something tells me it's not.

Unless there's yet another something magical that I don't know about.

**Comment by ardalis** [comment] 2022-02-02 15:28
Just brainstorming here...

You can absolutely convert types in the pipeline. Action filters are commonly used to do this. For example you could have a route that takes in a `customerId` but then have an action that has `Customer customer` as its parameter, and an Action Filter whose job was to read the customerId, look up the customer from the database, and then pass a `Customer` instance on to the action method/endpoint. I'm not saying you should necessarily go this route, just letting you know it's definitely possible.

As for adding tenantId to every request, you could create a BaseTenantRequest that has the `TenantId` property on it and then just have all your requests inherit from this type. That would involve minimal duplication. And if you combined this with the Action Filter approach you could check to see if the incoming request included a type that inherited from BaseTenantRequest and if so, pull the tenantId from a header.

**Comment by nhwilly** [comment] 2022-02-02 18:20
Thanks.  I prefer the latter as the problem just fades into the woodwork.  

I had planned to inherit it somehow, doesn't make sense to do that each time.  And I do want to force the behavior so I can't forget.

I'm just not certain how I would set the property on the request while still making the object immutable, unless I create a new constructor for that purpose, or I create a mapper from T to T that handles the inclusion of the tenantId.  It's either that, or a public setter for tenantId, right?

I'll figure it out - I just really like your approach on these kinds of things and I don't want to water them down with my unsophisticated coding skills.

They are forcing me to address everything up front and avoid stupid short cuts and I really like it.

Thanks, again.

**Comment by nhwilly** [comment] 2022-02-03 22:56
For anyone else...

I tried creating a generic that took the request object as a type parameter so that I could get the additional data at the endpoint without corrupting the actual request I wanted.  It looked like this:

```csharp
public class CreateAccountPermissionGroup : EndpointBaseAsync
  .WithRequest<TenantRequest<CreateAccountPermissionsGroupRequest>>
  .WithActionResult<CreateAccountPermissionsGroupResponse>
```

And I finally got the generic activation and all to work.  Pretty neat.  But the problem is I didn't realize that it was going to change the Swagger signature (duh) and more importantly, it attempts to bind to that generic type instead of the generic attribute type that I wanted.

It looked like this:
```csharp
public class TenantRequiredAttribute : ActionFilterAttribute
{
  public override void OnActionExecuting(ActionExecutingContext context)
  {
    var model = context.ActionArguments.Values.FirstOrDefault(x => x is BaseRequest);
    if (model == null) return;

    var ipAddress = context.HttpContext.Request.IpFromHeaders();
    var userId = context.HttpContext.User.LocalUserId() ?? "user id"; ;
    var userName = context.HttpContext.User.DisplayName() ?? "user display name"; 
    var tenantId = context.HttpContext.Request.TenantId();

    var requestMeta = new RequestMeta(userName, userId, ipAddress);

    Type requestType = typeof(TenantRequest<>).MakeGenericType(model.GetType());

    var tenantRequest = Activator.CreateInstance(requestType, new[] { model, tenantId, requestMeta });


    context.ActionArguments.Values.Add(tenantRequest);  // this doesn't work.  the collection is immutable.
    model = tenantRequest; // this doesn't work, either.
    
  }
}
```
But I don't believe you can change the incoming and outgoing types without messing up the binding.

This seems like it's getting out of hand, so I tried inheriting them and just setting the values in the model while it's in the filter.  

That does work, but the Swagger has to be modified to allow SwaggerUI to prompt for it, because the controller parameters can't accept any additional parameters, like `[FromHeader]` which would allow Swagger to pick it up and me to enter it.

Works with PostMan, though.

**Comment by ColinM9991** [comment] 2022-03-07 13:04
I've recently started migrating an application to using ApiEndpoints but this has stopped that progress dead in it's tracks.

What I have is an endpoint that accepts an ID in the URL (Route) and a JSON body that contains the remaining values for the model.

The only thing I receive in the endpoint is the ID since I'm using `FromRouteAttribute`. I have tried to use `FromMultiSource` but Body and Route can't be combined here since Body is known as `Greedy`.

**Closed** 2022-03-07 16:03 UTC

**Comment by ardalis** [comment] 2022-03-07 16:07
NOTE: Add this to docs / documentation

**Comment by zvaklinov** [comment] 2023-01-30 09:25
This still throws me a 404 Response error with no specific log. I did everything the same way you did, @ardalis , yet it doesn't even hit my breakpoint.

![image](https://user-images.githubusercontent.com/87761915/215438142-34dec069-cd7c-4711-8e01-276f260bf200.png)
